services:
  app_atmosphere:
    build: .
    volumes:
      - .:/home/atmosphere
      - vendor:/home/atmosphere/vendor
    working_dir: /home/atmosphere
    command: >
      sh -c "
      composer install &&
      if [ ! -d 'app/Providers/Filament' ]; then
        composer require filament/filament:^5.0 -W --no-audit --ignore-platform-req=php+ &&
        php artisan filament:install --panels --quiet;
      fi &&
      php artisan key:generate &&
      php artisan migrate --force &&
      php-fpm
      "
    depends_on:
      mysql_atmosphere:
        condition: service_healthy
    networks:
      - nginx_network # Общая сеть с вашим Nginx

  mysql_atmosphere:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata_atmosphere:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
    networks:
      - nginx_network

volumes:
  dbdata_atmosphere:
  vendor:

networks:
  nginx_network:
    external: true # Предполагаем, что сеть создана заранее для Nginx